### ISSUE TITLE
Inconsistent keymapping in Linux

### ISSUE THREAD

**Issue by CosmosAtlas** [rvaiya/warpd#91]
## Current behavior

When I use the shortcut to trigger `warpd`, the keymap read seems to be QWERTY, however, once I'm inside any modes, the keymap read is what I have set in X (i.e., programmer dvorak).

To illustrate the problem, I'll introduce some relevant mappings between QWERTY and programmer dvorak (DVP) .

| *Physical* | QWERTY | DVP |
|--|-|---|
|*X*|X|Q|
|*U*|U|G|
|*K*|K|T|
|*G*|G|I|
|*F*|F|U|

So it means that, when I press a physical key labelled X on the keyboard, the input to the computer will be Q. To avoid confusion, I'll use italic letters from now on as the physical key. 

Now, pressing *A-M-G* will trigger `warpd` which is the representation of QWERTY.

However, from now on, I'll need to press *F* to select one of the grids, which is the representation of U in DVP.

When I do switch the layout to QWERTY via `setxkbmap`, `warpd` will use QWERTY correctly.

## What I expect

I would expect that during operation `warpd` would operate on a single keymap for different modes. Say both triggering and after uses QWERTY.

## Feature request

It would be nice if this can be tweaked. For example, for my particular setup with `sxhkd` (a global shortcut manager), it always read the keys in QWERTY, regardless of the layout (e.g., QWERTY, or DVP). So switching between layouts won't affect the memory of which physical key to press.

## My setup

I'll list my setup here incase something is interfering with `warpd`.

I'm currently running `warpd` in DWM in Arch Linux. I run `sxhkd` in the backgroud with QWERTY and ignores any `setxkbmap` change events.

**Comment by rvaiya** [comment]
Thanks for the detail. I believe this should be fixed in the latest commit.

**Comment by CosmosAtlas** [comment]
I tried the newest version. It does work as expected.

However, I tried to change the xkblayout when warpd is running, and now pressing the activate key seems to freeze my keyboard. That is at this moment, pressing any key on my keyboard doesn't do anything.

Strangely, after replugging in the keyboard, I regain control of my keyboard. But warpd still does nothing.

**Comment by rvaiya** [comment]
Changing keyboard layouts via xkb while warpd is running is unsupported. The input system uses several hacks to work around X limitations. If you are in the habit of switching layouts, I would advise you to use an evdev remapper like keyd, which bypasses the X layer altogether.

**Comment by CosmosAtlas** [comment]
Thanks for the explanation, it makes much sense. 

Also after looking at keyd, it seems like an awesome software. It looks easier to configure than something like `caps2esc`. And since it's low level enough, X or wayland shoudn't matter.

Now I  need to figure out how to map programmer dvorak keys with it when I have time.. I'll bug you with an issue there if I encounter any problems down the road.
